name: openapp
description: "An Open Root-Corporation Flutter project."
publish_to: 'none'

version: 0.1.3

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  go_router: ^16.2.1
  haptic_feedback: ^0.5.0
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  device_info_plus: ^11.1.1
  connectivity_plus: ^7.0.0
  font_awesome_flutter: ^10.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.12

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/legals/

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true